### PR TITLE
replace glide with go modules

### PR DESCRIPTION
**Pull request by przemeklal**
Userspace CNI plugin dependencies on go packages were handled by 'glide' project. However 'glide' is not maintained anymore and it is recommended to switch to the go official tool 'go modules' instead.

In order to replace glide by 'go modules', following has been done:
* go version was updated to 1.14 to get stable and production ready version of go modules
* glide.yaml and glide.lock were used to generate go.mod and go.sum, i.e. to use the same version of packages at the beginning
* govpp (go specific VPP API) was updated to recent version 0.3.5.
* govpp bin api generation was updated and generated files moved into cnivpp/bin_api to avoid issues during execution of go mod commands, which were trying to satisfy dependency (imports) on generated api.
* bin api generation was moved to separate Makefile target, which is called automatically when needed
* vendor directory with module cache was removed from the repository, because 'go modules' has its own caching system, which avoids collisions among different versions of the same package used by different go projects
* documentation was updated
* remaining glide files were removed and dependencies were updated to more recent versions

Signed-off-by: Martin Klozik <martinx.klozik@intel.com>

### CODE REVIEW

**Comment by przemeklal** [comment]
The only open question is whether we want to keep the `vendor` directory. I'd prefer to get rid of it, but if the team decides to keep it then it's just a matter of running `go mod vendor` and pushing it back here.

**Comment by Billy99** [comment]
I asked around on our group slack and they recommended keeping `/ vendor`. That was for downstream OpenShift. However, there are no plans for this on OpenShift. All the projects I work with have `/vendor` checked in and I would lean towards checking it in. That being said, I am not a GO expert, so I would defer to others.

**Comment by przemeklal** [comment]
I think there's an issue with autogenerated VPP binapi that doesn't seem to play nicely with Go modules. After running `go mod vendor` make build starts to fail because go expects the autogenerated code to be vendored too and it's not. We could copy and paste it there, but it can be problematic to maintain in long term. SRIOV-CNI dropped vendor dir some time ago after adding support for go mod, so we should be fine without it. @garyloug what do you think?

**Comment by garyloug** [comment]
@przemeklal @Billy99 I'm ok with removing it, especially if it resolves the VPP bin issues. Have had quite a few people message me internally with these build issues. I say lets remove it, it can easily be regenerated with `go mod vendor` if we need it back.

**Comment by Billy99** [comment]
Let remove it then.

**Pull request merged**
