### PR TITLE
Bump kubernetes dependencies to v0.18.3

### PR DESCRIPTION
**Pull request by Billy99**
multus-cni and network-attachment-definition-client moved their dependencies, so
app-netutil won't build unless userspace-cni-network-plugin also is updated.

Signed-off-by: Billy McFall <22157057+Billy99@users.noreply.github.com>

### CODE REVIEW

**Comment by Billy99** [comment]
@garyloug @przemeklal PTAL

**Comment by garyloug** [comment]
@Billy99 LGTM. I need to build and test a bunch of changes from @patrickog11 this week. I can include this too.

Question on the context.TODO() - is this something we need to come back and address later? Do you see us passing an actual context in future? Or should this be context.Background() ?

**Comment by Billy99** [comment]
@garyloug With reagrds to context.TODO(), I wrote you on Intel slack (long post). If we move completely to the device-info-spec, we won't need any of this code.

**Comment by Billy99** [comment]
@garyloug Any feedback? Need this upstream before I can push my app-netutil changes.

**Comment by garyloug** [comment]
@Billy99 sorry haven't been keeping an eye on Slack. Just reinstalled and read your post. Makes sense, will merge this.

**Pull request merged**
