### PR TITLE
Add Checkov action

### PR DESCRIPTION
**Pull request by Eoghan1232**

### CODE REVIEW

**Comment by Eoghan1232** [comment]
looks like Checkov found a valid issue, so it is working.

I will resign the commits and push in a moment.

**Comment by johnoloughlin** [comment]
we need to ignore CKV_K8S_12: "Memory requests should be set"

**Comment by Eoghan1232** [comment]
should we merge or leave so?

**Comment by Eoghan1232** [comment]
No longer needed

**Pull request closed without merging**
